# Enable live reload for styles and config when changes are saved
watch_stylesheet: true
watch_config: true
debug: false

# Komorebi tiling window manager commands
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

# Bar configuration
bars:
  primary-bar:
    enabled: true
    screens: ["*"]  # Show on all screens
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 24
    padding:
      top: 4
      left: 4
      bottom: 0
      right: 4
    widgets:
      left: ["menu_widget", "apps", "active_window"]
      center: ["komorebi_workspaces"]
      right: ["taskbar", "whkd", "wallpapers", "weather", "volume", "clock", "power_menu"]

# Widget definitions
widgets:

  # Shows the currently active window
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: "..."
      monitor_exclusive: true

  # Clock widget
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M %a}"
      label_alt: "{%A, %d %B %Y %H:%M}"

  # Komorebi workspace switcher
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_workspace_btn: "{index}"
      animation: true
      container_padding: {top: 0, left: 1, bottom: 0, right: 1}

  # Weather widget (API key required)
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "YOUR_API_KEY_HERE"
      update_interval: 1200
      location: "Your City Name Here"

  # Volume control
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      volume_icons:
        - "\ueee8"  # Muted
        - "\uf026"  # 0-10%
        - "\uf027"  # 11-60%
        - "\uf028"  # 61-100%
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  # Power menu
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      blur_background: true
      animation_duration: 200
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]

  # Application launcher bar
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding: {top: 0, left: 0, bottom: 0, right: 0}
      label: "{data}"
      app_list:
        # 🗑️ Recycle Bin
        - {icon: "\uf2ed", launch: "cmd.exe /c start shell:RecycleBinFolder"}
        # 🔔 Notification Center
        - {icon: "\uf0a2", launch: "cmd.exe /c start ms-actioncenter:"}
        # ⚙️ Quick Settings, Search, Task Manager, Terminal
        - {icon: "\ueb51", launch: "quick_settings"}
        - {icon: "\uf422", launch: "search"}
        - {icon: "\ueb03", launch: "cmd /c Taskmgr"}
        - {icon: "\uf489", launch: "wt"}

        # 🧑‍💻 Common Apps (Update paths as needed)
        - {icon: "\uf1ff", launch: "C:\\Users\\YourUsername\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe"}
        - {icon: "\udb80\ude39", launch: "C:\\Program Files\\Mozilla Firefox\\firefox.exe"}
        - {icon: "\uf408", launch: "C:\\Users\\YourUsername\\AppData\\Local\\GitHubDesktop\\GitHubDesktop.exe"}
        - {icon: "\uf1bc", launch: "C:\\Users\\YourUsername\\AppData\\Roaming\\Spotify\\Spotify.exe"}
        - {icon: "\uf07b", launch: "explorer.exe"}
        - {icon: "\uf48a", launch: "C:\\Users\\YourUsername\\AppData\\Local\\Programs\\Obsidian\\Obsidian.exe"}

  # WHKD (hotkey daemon) icon
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"

  # "Menu" text button
  menu_widget:
    type: "yasb.custom.CustomWidget"
    options:
      label: "Menu"
      class_name: "custom-menu-widget"
      callbacks:
        on_left: "exec start_menu"

  # Taskbar (running apps)
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 16

  # Wallpaper picker
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\YourUsername\\Pictures\\Wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after:
        - "wal -s -t -e -q -n -i {image}"
        - "cmd.exe /c start /min pwsh ./yasb.ps1"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
